[project]
name = "sematic"
description = "Sematic ML orchestration tool"

# The formatting of this line must be maintained for version testing.
version = "0.41.0"
requires-python = ">=3.9, <3.14"
dependencies = [
  # System
  "ipython==8.2.0",
  "setuptools==58.1.0",

  # DB
  "SQLAlchemy>=2.0",
  "psycopg2-binary>=2.9.5",

  # Code
  "pyyaml>=6.0.1",
  "python-magic>=0.4.27",

  # Git integration
  "git-python>=1.0.3",

  # Build system
  "docker>=6.0.0",

  # Client
  "websocket-client>=1.5.1",
  "python-socketio>=5.7.2",

  # API server
  "flask>=2.2.2",
  "flask-cors>=3.0.10",
  "cloudpickle>=2.2.1",
  "requests>=2.28.2",
  "werkzeug>=2.2.3",
  "python-dateutil>=2.8.2",
  "starlette>=0.25.0",
  "google-auth>=2.16.0",
  "uvicorn[standard]>=0.20.0",
  "asgiref>=3.7.2",

  # CLI
  "click>=8.1.3",

  # Cloud execution
  "kubernetes>=25.3.0",
  "boto3>=1.26.82",
  "google-cloud-storage>=2.10.0",
  "types-google-cloud-ndb>=2.2.0.0",

  # General
  "boltons>=23.0.0"
]

[tool.isort]
profile = "black"
import_heading_stdlib="Standard Library"
import_heading_firstparty="Sematic"
import_heading_thirdparty="Third-party"
known_third_party = ["flask", "psycopg2", "matplotlib", "cloudpickle"]
multi_line_output = 3


[tool.poetry]
name = "sematic"
version = "0.141.1"
license = "Apache License 2.0"
description = "An open-source ML pipeline development platform"
homepage = "https://sematic.dev"
readme = "README.md"
authors = ["Sematic AI, Inc."]
maintainers = ["Sematic AI <support@sematic.dev>"]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Visualization",
    "Typing :: Typed",
]

[tool.poetry.scripts]
sematic = "sematic.cli.main:cli"

[tool.poetry.dependencies]
python = ">=3.10, <3.13"

# DB
sqlalchemy = ">=2.0"
psycopg2-binary = "*"

# Code
pyyaml = "6.0.1"

# Git integration
git-python = "*"

# Build system
docker = "*"

# Client
websocket-client = "*"
python-socketio = "*"

# API server
flask = "*"
flask-cors = "*"
cloudpickle = "*"
requests = "*"
werkzeug = "*"
python-dateutil = "*"
starlette = "*"
google-auth = "*"
uvicorn = { version = "*", extras = ["standard"] }
asgiref = "*"

# CLI
click = "*"

# Types
snowflake-connector-python = "*"
pyopenssl = "*"
pyarrow = ">=12.0.0"

# Cloud execution
kubernetes = "*"
boto3 = "*"
google-cloud-storage = "*"
python-magic = "*"


[tool.poetry.group.dev.dependencies]
# Tests
pytest = "7.1.1"
testing-postgresql = "*"
coveragepy = { git = "https://github.com/ulfjack/coveragepy.git", branch = "lcov-support" }

# System
debugpy = "*"
ipython = "*"

# Code
pyright = "*"
isort = "*"

[tool.poetry.group.examples]
optional = true

[tool.poetry.group.examples.dependencies]
torch = "1.13.1"
torchvision = "0.14.1"
pytorch-lightning = "*"
ray-lightning = "*"
torchmetrics = "*"
plotly = "*"
pandas = "*"
pandas-stubs = "*"
seaborn = "*"
matplotlib = "*"
statsmodels = "*"
scikit-learn = "*"
numpy = ">=1.24.0"
xgboost = "*"
accelerate = "*"
datasets = ">=2.12.0"
huggingface-hub = "*"
peft = "*"
transformers = "*"
gradio = "*"
trafilatura = "*"
cohere = "*"
openai = "*"

[tool.poetry.group.ray]
optional = true

[tool.poetry.group.ray.dependencies]
ray = { version = ">=2.3.0", extras = ["default", "air"] }
cython = "0.29.33"

[tool.poetry.extras]
ray = ["ray", "cython"]
examples = [
  "torch",
  "torchvision",
  "pytorch-lightning",
  "ray-lightning",
  "torchmetrics",
  "plotly",
  "pandas",
  "pandas-stubs",
  "seaborn",
  "matplotlib",
  "statsmodels",
  "scikit-learn",
  "numpy",
  "xgboost",
  "accelerate",
  "datasets",
  "huggingface-hub",
  "peft",
  "transformers",
  "gradio",
  "trafilatura",
  "cohere",
  "openai",
]

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools", "setuptools-scm"]
build-backend = "poetry.core.masonry.api"

[tool.setuptools]
py-modules = [
  "sematic",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["sematic*"]
exclude = ["tests*", "*.tests*"]

[tool.setuptools.package-data]
sematic = ["sematic/ui/build/**/*"]

[project.scripts]
sematic = "sematic.cli.main:cli"

[project.optional-dependencies]
examples = [
  # Examples
  # Most libraries that require python version < 3.13
  # are marked as such because they do not yet have
  # full support for python 3.13. Once they do, this restriction
  # can be removed.
  "snowflake-connector-python==3.12.4; python_version < '3.13'",
  "pyOpenSSL>=23.0.0",
  "pyarrow>=12.0.0; python_version < '3.13'",
  "python-magic==0.4.27",
  "torch>=1.13.1; python_version < '3.13'",
  "torchvision>=0.14.1; python_version < '3.13'",
  "pytorch-lightning>=1.6.5; python_version < '3.13'",
  "ray-lightning>=0.3.0; python_version < '3.13'",
  "plotly==5.13.0; python_version < '3.13'",
  "pandas>=1.5.3; python_version < '3.13'",
  "seaborn>=0.12.2; python_version < '3.13'",
  "matplotlib>=3.7.0; python_version < '3.13'",
  "statsmodels>=0.13.5; python_version < '3.13'",
  "scikit-learn>=1.2.1; python_version < '3.13'",
  "numpy>=1.24.0; python_version < '3.13'",
  "xgboost>=1.7.3; python_version < '3.13'",
  "accelerate==0.19.0; python_version < '3.13'",
  "datasets>=2.12.0; python_version < '3.13'",
  "huggingface-hub>=0.14.1",
  "peft>=0.3.0; python_version < '3.13'",
  "transformers>=4.29.2; python_version < '3.13'",
  "gradio>=3.35.2; python_version < '3.13'",
  "trafilatura>=1.6.0",
  "cohere>=4.9.0",
  "openai>=0.27.8",
]

ray = [
  # External Resource Plugins
  ## Ray
  # Note: just because we depend on ray[air] here does NOT
  # mean our wheel depends on it, nor does it imply that users
  # will/will not have ray[air]. This is only about what is present
  # in Sematic's dev workspace.
  "ray[default,air]>=2.3.0; python_version < '3.13'",
]

all = [
  "ray[default,air]>=2.3.0; python_version < '3.13'",
]

[tool.uv]
dev-dependencies = [
  "testing-postgresql>=1.3.0",
  "debugpy>=1.6.6",
  "pandas-stubs>=2.2.2; python_version < '3.13'",
  "mypy==1.11.1",
  "ruff-lsp==0.0.35",
  "python-lsp-ruff>=2.2.2",
  "python-lsp-server>=1.11.0",
  "pytest==7.4.0",
  "pathspec==0.11.2",
  "mypy-extensions==1.0.0",
  "platformdirs==3.10.0",
  "responses==0.18.0",
]

[tool.ruff]
line-length = 90

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.ruff.lint.isort]
known-first-party = ["sematic"]

# Use a single line after each import block.
lines-after-imports = 2

[tool.pylsp.plugins.ruff]
enabled = true

[[tool.mypy.overrides]]
module = "boto3.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "botocore.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "yaml.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "transformers.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "torch.*"
ignore_missing_imports = true

[tool.mypy]
exclude = ".*site-packages.*"

[tool.uv.sources]
sematic = { workspace = true }

[tool.pytest.ini_options]
testpaths = [
  "sematic",
]

