# Standard Library
import contextlib
from contextvars import ContextVar
from typing import Any, Iterator, TypeVar, Union

# Sematic
from sematic.utils.typeutils import make_sentinel

NOT_SET = make_sentinel(name="NOT_SET")
T = TypeVar("T")


def get_ctx_var_value_with_fallback(context_var: ContextVar[T]) -> Union[T, Any]:
    """Get the value of a ContextVar with a fallback Sentinel value.

    Notes
    -----
    We can't just call context_var.get(NOT_SET) because that supersedes
    the ContextVar's default value, if any.
    """
    try:
        return context_var.get()
    except LookupError:
        return NOT_SET


@contextlib.contextmanager
def temp_set_context_vars(context_vars_to_values: dict[ContextVar[T], T]) -> Iterator:
    """Temporarily set input ContextVariables to be values for the scope of this contextmanager."""
    # TODO (BCal) we originally tracked per-context-var tokens generated by context_var.set(new_value)
    #  and then called context_var.reset(<token>) after the yield, but this would sometimes hit the exception
    #  ValueError: <Token var=...> was created in a different Context
    #  To get around that, we're avoiding tracking the tokens and instead just tracking the original values
    #  That means this is probably not good to repeatedly call this context manager
    #  The action-item is to figure out why these ValueErrors were/are getting triggered,
    #  where my confusion stems from the (maybe naive) assumption that everything that happens
    #  within the scope of this contextmanager should be restricted to one literal Context

    prior_values = {
        context_var: get_ctx_var_value_with_fallback(context_var)
        for context_var in context_vars_to_values.keys()
    }
    for context_var, new_value in context_vars_to_values.items():
        context_var.set(new_value)
    try:
        yield
    finally:
        for context_var, prior_value in prior_values.items():
            context_var.set(prior_value)
